title: Galay Blog
SEOTitle: Galay的博客 | Galay Blog
header-img: img/post-bg-desk.jpg
description: "Every failure is leading towards success."
url: "http://tjcrt.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
